apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-controller-operatorsdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sample-controller-operatorsdk
  template:
    metadata:
      labels:
        name: sample-controller-operatorsdk
    spec:
      serviceAccountName: sample-controller-operatorsdk
      containers:
        - name: sample-controller-operatorsdk
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - sample-controller-operatorsdk
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sample-controller-operatorsdk"
